import type { Job } from '../types'

export const jobs: Job[] = [
  {
    id: 'job-001',
    title: 'Logo refresh for organic skincare DTC brand',
    source: 'email',
    budget: '$800 – $1,200',
    budgetType: 'fixed',
    description:
      'We are launching a new product line and need a refined logo that feels premium and natural. Deliverables include primary logo, icon mark, and a one-page usage guide.',
    skills: ['Logo Design', 'Brand Identity', 'Adobe Illustrator'],
    clientQuality: 'high',
    clientInfo: { spend: '$12K+', rating: 4.9, location: 'United States', hireRate: '85%' },
    competition: 'medium',
    matchScore: 88,
    verdict: 'apply',
    scoreBreakdown: {
      nicheMatch: 92,
      budgetQuality: 85,
      clientQuality: 90,
      competition: 70,
      clarity: 88,
      urgency: 75,
      portfolioMatch: 95,
      conversionChance: 82,
    },
    redFlags: [],
    portfolioMatchIds: ['port-001'],
    suggestedAngle: 'Lead with Verdant Botanicals case study — same organic skincare vertical.',
    discoveryQuestion: 'Are you keeping existing brand colors or open to a full palette refresh?',
    postedDate: '2026-06-10T09:00:00Z',
    receivedDate: '2026-06-10T09:14:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~0123456789',
    stage: 'replied',
    outcome: null,
  },
  {
    id: 'job-002',
    title: 'Complete brand identity for B2B analytics SaaS',
    source: 'apify',
    budget: '$3,000 – $5,000',
    budgetType: 'fixed',
    description:
      'Early-stage SaaS needs a full identity system: logo, color palette, typography, icon style, and pitch deck template. Must scale from startup to enterprise.',
    skills: ['Brand Identity', 'Logo Design', 'Presentation Design'],
    clientQuality: 'high',
    clientInfo: { spend: '$45K+', rating: 4.8, location: 'Canada', hireRate: '72%' },
    competition: 'high',
    matchScore: 84,
    verdict: 'apply',
    scoreBreakdown: {
      nicheMatch: 88,
      budgetQuality: 95,
      clientQuality: 92,
      competition: 55,
      clarity: 90,
      urgency: 80,
      portfolioMatch: 78,
      conversionChance: 76,
    },
    redFlags: ['High competition — 20+ proposals likely'],
    portfolioMatchIds: ['port-002', 'port-005'],
    suggestedAngle: 'Emphasize scalable identity systems and tech startup experience from winning SaaS proposal.',
    discoveryQuestion: 'Do you have an existing product UI that the brand needs to align with?',
    postedDate: '2026-06-08T14:30:00Z',
    receivedDate: '2026-06-08T14:45:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~9876543210',
    stage: 'hired',
    outcome: null,
  },
  {
    id: 'job-003',
    title: 'Product packaging labels for craft hot sauce line',
    source: 'api',
    budget: '$600 – $900',
    budgetType: 'fixed',
    description:
      'Three flavor variants need bold, shelf-ready label designs. Must include dielines and print-ready PDFs. Rustic-but-modern aesthetic preferred.',
    skills: ['Packaging Design', 'Label Design', 'Print Design'],
    clientQuality: 'medium',
    clientInfo: { spend: '$3K+', rating: 4.6, location: 'United States', hireRate: '60%' },
    competition: 'low',
    matchScore: 91,
    verdict: 'apply',
    scoreBreakdown: {
      nicheMatch: 95,
      budgetQuality: 80,
      clientQuality: 72,
      competition: 90,
      clarity: 92,
      urgency: 85,
      portfolioMatch: 98,
      conversionChance: 88,
    },
    redFlags: [],
    portfolioMatchIds: ['port-003'],
    suggestedAngle: 'Direct Luma Sparkling Water packaging match — same multi-variant CPG challenge.',
    discoveryQuestion: 'Do you already have bottle dimensions and printer specs?',
    postedDate: '2026-06-12T11:00:00Z',
    receivedDate: '2026-06-12T11:02:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~5551234567',
    stage: 'interview',
    outcome: null,
  },
  {
    id: 'job-004',
    title: 'Snack brand packaging design — chips & puffs line',
    source: 'manual',
    budget: '$1,000 – $1,500',
    budgetType: 'fixed',
    description:
      'New DTC snack brand entering Whole Foods needs eye-catching bag design for two SKUs. Brand name finalized, need visual identity and packaging.',
    skills: ['Packaging Design', 'Brand Identity', 'Illustration'],
    clientQuality: 'medium',
    clientInfo: { spend: '$8K+', rating: 4.7, location: 'United States', hireRate: '68%' },
    competition: 'medium',
    matchScore: 86,
    verdict: 'apply',
    scoreBreakdown: {
      nicheMatch: 90,
      budgetQuality: 88,
      clientQuality: 75,
      competition: 68,
      clarity: 85,
      urgency: 90,
      portfolioMatch: 92,
      conversionChance: 80,
    },
    redFlags: [],
    portfolioMatchIds: ['port-003', 'port-002'],
    suggestedAngle: 'Position as CPG specialist with retail-ready deliverables and fast timeline.',
    discoveryQuestion: 'Is the brand illustration style decided, or part of this scope?',
    postedDate: '2026-06-13T16:00:00Z',
    receivedDate: '2026-06-13T16:00:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~4449876543',
    stage: 'drafted',
    outcome: null,
  },
  {
    id: 'job-005',
    title: 'Minimalist logo for meditation app',
    source: 'email',
    budget: '$400 – $600',
    budgetType: 'fixed',
    description:
      'Need a calm, modern logo for a mobile meditation app. Soft gradients okay. App icon + wordmark required.',
    skills: ['Logo Design', 'Mobile Design', 'Icon Design'],
    clientQuality: 'medium',
    clientInfo: { spend: '$2K+', rating: 4.5, location: 'United Kingdom', hireRate: '55%' },
    competition: 'high',
    matchScore: 72,
    verdict: 'apply',
    scoreBreakdown: {
      nicheMatch: 78,
      budgetQuality: 65,
      clientQuality: 68,
      competition: 45,
      clarity: 82,
      urgency: 70,
      portfolioMatch: 70,
      conversionChance: 62,
    },
    redFlags: ['Budget on lower end for scope', 'High competition expected'],
    portfolioMatchIds: ['port-001'],
    suggestedAngle: 'Offer a streamlined 3-concept process to stand out on budget.',
    discoveryQuestion: 'Will the logo need to work as a standalone app icon at 1024px?',
    postedDate: '2026-06-14T08:00:00Z',
    receivedDate: '2026-06-14T08:22:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~3331112222',
    stage: 'found',
    outcome: null,
  },
  {
    id: 'job-006',
    title: 'Brand style guide for boutique hotel chain',
    source: 'apify',
    budget: '$2,500 – $4,000',
    budgetType: 'fixed',
    description:
      'Three-property boutique hotel group needs a unified brand guide covering logo usage, photography style, signage, and guest touchpoints.',
    skills: ['Brand Identity', 'Brand Guidelines', 'Hospitality Design'],
    clientQuality: 'high',
    clientInfo: { spend: '$20K+', rating: 4.9, location: 'Spain', hireRate: '78%' },
    competition: 'medium',
    matchScore: 79,
    verdict: 'apply',
    scoreBreakdown: {
      nicheMatch: 82,
      budgetQuality: 92,
      clientQuality: 88,
      competition: 65,
      clarity: 78,
      urgency: 60,
      portfolioMatch: 75,
      conversionChance: 70,
    },
    redFlags: [],
    portfolioMatchIds: ['port-002'],
    suggestedAngle: 'Reference Northline Coffee hospitality-adjacent branding and signage experience.',
    discoveryQuestion: 'Are the three properties sharing one logo or sub-brand variations?',
    postedDate: '2026-06-07T10:00:00Z',
    receivedDate: '2026-06-07T10:18:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~2223334444',
    stage: 'viewed',
    outcome: null,
  },
  {
    id: 'job-007',
    title: 'Instagram template pack for luxury real estate team',
    source: 'email',
    budget: '$500 – $800',
    budgetType: 'fixed',
    description:
      'Real estate team needs 15 Canva templates for listings, open houses, and agent profiles. Must feel luxury and on-brand.',
    skills: ['Social Media Design', 'Canva', 'Real Estate Marketing'],
    clientQuality: 'medium',
    clientInfo: { spend: '$5K+', rating: 4.4, location: 'United States', hireRate: '62%' },
    competition: 'medium',
    matchScore: 68,
    verdict: 'maybe',
    scoreBreakdown: {
      nicheMatch: 72,
      budgetQuality: 70,
      clientQuality: 65,
      competition: 60,
      clarity: 75,
      urgency: 55,
      portfolioMatch: 80,
      conversionChance: 58,
    },
    redFlags: ['Canva-only deliverable — lower margin work'],
    portfolioMatchIds: ['port-004'],
    suggestedAngle: 'Strong Studio Arc social kit match, but evaluate ROI vs. brand identity projects.',
    discoveryQuestion: 'Do you have brand colors and fonts locked, or need those defined too?',
    postedDate: '2026-06-11T13:00:00Z',
    receivedDate: '2026-06-11T13:35:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~6667778888',
    stage: 'found',
    outcome: null,
  },
  {
    id: 'job-008',
    title: 'Rebrand exploratory — fintech mobile app',
    source: 'api',
    budget: null,
    budgetType: 'unknown',
    description:
      'Looking for a designer to explore visual directions for our fintech app rebrand. Budget flexible depending on experience. Need moodboards first.',
    skills: ['UI/UX Design', 'Brand Identity', 'Fintech'],
    clientQuality: 'unknown',
    clientInfo: { spend: 'Unknown', rating: undefined, location: 'Singapore', hireRate: undefined },
    competition: 'high',
    matchScore: 55,
    verdict: 'maybe',
    scoreBreakdown: {
      nicheMatch: 60,
      budgetQuality: 30,
      clientQuality: 40,
      competition: 35,
      clarity: 50,
      urgency: 45,
      portfolioMatch: 55,
      conversionChance: 42,
    },
    redFlags: ['No budget listed', 'Client history unknown', 'Scope vague — moodboards only?'],
    portfolioMatchIds: ['port-005'],
    suggestedAngle: 'Could be high-value if budget materializes — ask for range before investing time.',
    discoveryQuestion: 'What budget range have you allocated for the full rebrand vs. exploratory phase?',
    postedDate: '2026-06-13T02:00:00Z',
    receivedDate: '2026-06-13T02:05:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~7778889999',
    stage: 'found',
    outcome: null,
  },
  {
    id: 'job-009',
    title: 'Event flyer and social graphics for music festival',
    source: 'manual',
    budget: '$200 – $350',
    budgetType: 'fixed',
    description:
      'One-time event needs a flyer, Instagram posts, and story templates. Edgy, colorful, music-festival vibe. Quick turnaround.',
    skills: ['Graphic Design', 'Flyer Design', 'Social Media Design'],
    clientQuality: 'low',
    clientInfo: { spend: '$800+', rating: 3.8, location: 'United States', hireRate: '40%' },
    competition: 'high',
    matchScore: 38,
    verdict: 'maybe',
    scoreBreakdown: {
      nicheMatch: 35,
      budgetQuality: 25,
      clientQuality: 30,
      competition: 40,
      clarity: 70,
      urgency: 95,
      portfolioMatch: 25,
      conversionChance: 28,
    },
    redFlags: ['Below typical rate', 'Outside core portfolio vertical', 'Low client rating'],
    portfolioMatchIds: [],
    suggestedAngle: 'Only pursue if pipeline is slow — not aligned with brand identity focus.',
    discoveryQuestion: 'Is this a one-off or could it lead to annual festival work?',
    postedDate: '2026-05-28T18:00:00Z',
    receivedDate: '2026-05-28T18:00:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~1110009999',
    stage: 'archived',
    outcome: null,
  },
  {
    id: 'job-010',
    title: 'Wine label design for small vineyard',
    source: 'apify',
    budget: '$700 – $1,000',
    budgetType: 'fixed',
    description:
      'Family vineyard launching first commercial line needs an elegant wine label for two varietals. Classic, premium feel with modern touches.',
    skills: ['Packaging Design', 'Label Design', 'Print Design'],
    clientQuality: 'medium',
    clientInfo: { spend: '$4K+', rating: 4.5, location: 'France', hireRate: '58%' },
    competition: 'low',
    matchScore: 74,
    verdict: 'maybe',
    scoreBreakdown: {
      nicheMatch: 80,
      budgetQuality: 75,
      clientQuality: 70,
      competition: 85,
      clarity: 72,
      urgency: 50,
      portfolioMatch: 85,
      conversionChance: 65,
    },
    redFlags: ['New vertical — wine vs. existing CPG portfolio'],
    portfolioMatchIds: ['port-003'],
    suggestedAngle: 'Packaging skills transfer well — worth a premium proposal if time allows.',
    discoveryQuestion: 'Do you have regulatory text requirements for the label layout?',
    postedDate: '2026-06-09T07:00:00Z',
    receivedDate: '2026-06-09T07:12:00Z',
    jobUrl: null,
    stage: 'found',
    outcome: null,
  },
  {
    id: 'job-011',
    title: 'LinkedIn banner and profile kit for executive coach',
    source: 'manual',
    budget: '$300 – $450',
    budgetType: 'fixed',
    description:
      'Executive coach needs a cohesive LinkedIn banner, profile photo overlay frame, and 5 post templates. Professional, warm, authoritative.',
    skills: ['Social Media Design', 'LinkedIn', 'Personal Branding'],
    clientQuality: 'medium',
    clientInfo: { spend: '$1.5K+', rating: 4.3, location: 'Australia', hireRate: '50%' },
    competition: 'medium',
    matchScore: 61,
    verdict: 'maybe',
    scoreBreakdown: {
      nicheMatch: 58,
      budgetQuality: 55,
      clientQuality: 62,
      competition: 58,
      clarity: 80,
      urgency: 65,
      portfolioMatch: 68,
      conversionChance: 52,
    },
    redFlags: [],
    portfolioMatchIds: ['port-004'],
    suggestedAngle: 'Adapt social kit approach from Studio Arc — smaller scope, quick win potential.',
    discoveryQuestion: 'Do you have professional headshots, or is photo direction part of the scope?',
    postedDate: '2026-06-12T20:00:00Z',
    receivedDate: '2026-06-12T20:00:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~8889990000',
    stage: 'drafted',
    outcome: null,
  },
  {
    id: 'job-012',
    title: 'Free test logo — "see if we vibe" before hiring',
    source: 'email',
    budget: '$50 – $100',
    budgetType: 'fixed',
    description:
      'Want to see your style first. Send one logo concept for our tech startup and if we like it we will hire for full project.',
    skills: ['Logo Design'],
    clientQuality: 'low',
    clientInfo: { spend: '$200+', rating: 3.2, location: 'India', hireRate: '15%' },
    competition: 'high',
    matchScore: 22,
    verdict: 'skip',
    scoreBreakdown: {
      nicheMatch: 40,
      budgetQuality: 10,
      clientQuality: 15,
      competition: 20,
      clarity: 60,
      urgency: 30,
      portfolioMatch: 35,
      conversionChance: 12,
    },
    redFlags: ['Spec work request', 'Extremely low budget', 'Low client rating', 'Low hire rate'],
    portfolioMatchIds: [],
    suggestedAngle: 'Do not engage — classic spec work pattern.',
    discoveryQuestion: '',
    postedDate: '2026-06-14T06:00:00Z',
    receivedDate: '2026-06-14T06:08:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~0001112222',
    stage: 'found',
    outcome: null,
  },
  {
    id: 'job-013',
    title: 'Full website design + branding — unrealistic scope',
    source: 'apify',
    budget: '$500 fixed',
    budgetType: 'fixed',
    description:
      'Need complete website (10 pages), logo, brand guide, social templates, and packaging. Must match reference sites provided. Unlimited revisions.',
    skills: ['Web Design', 'Brand Identity', 'Packaging Design', 'WordPress'],
    clientQuality: 'low',
    clientInfo: { spend: '$1K+', rating: 3.5, location: 'Pakistan', hireRate: '25%' },
    competition: 'high',
    matchScore: 18,
    verdict: 'skip',
    scoreBreakdown: {
      nicheMatch: 30,
      budgetQuality: 5,
      clientQuality: 20,
      competition: 25,
      clarity: 40,
      urgency: 50,
      portfolioMatch: 20,
      conversionChance: 8,
    },
    redFlags: [
      'Scope far exceeds budget',
      'Unlimited revisions',
      'Multi-discipline unrealistic for price',
    ],
    portfolioMatchIds: [],
    suggestedAngle: 'Auto-skip — scope/budget mismatch is extreme.',
    discoveryQuestion: '',
    postedDate: '2026-06-01T12:00:00Z',
    receivedDate: '2026-06-01T12:30:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~1231231234',
    stage: 'rejected',
    outcome: null,
  },
  {
    id: 'job-014',
    title: 'NFT collection artwork — 10,000 generative pieces',
    source: 'api',
    budget: null,
    budgetType: 'unknown',
    description:
      'Looking for artist to create traits and generative NFT collection. Must have crypto experience. Revenue share offered.',
    skills: ['NFT', 'Illustration', 'Generative Art'],
    clientQuality: 'unknown',
    clientInfo: {},
    competition: 'medium',
    matchScore: 12,
    verdict: 'skip',
    scoreBreakdown: {
      nicheMatch: 5,
      budgetQuality: 10,
      clientQuality: 25,
      competition: 50,
      clarity: 35,
      urgency: 20,
      portfolioMatch: 5,
      conversionChance: 5,
    },
    redFlags: [
      'NFT / crypto — on avoid list',
      'No fixed budget — revenue share only',
      'No job URL available',
    ],
    portfolioMatchIds: [],
    suggestedAngle: 'Hard skip per profile fingerprint avoid list.',
    discoveryQuestion: '',
    postedDate: '2026-06-11T00:00:00Z',
    receivedDate: '2026-06-11T00:01:00Z',
    jobUrl: null,
    stage: 'found',
    outcome: null,
  },
  {
    id: 'job-015',
    title: 'Copy-paste logo from reference image',
    source: 'manual',
    budget: '$75',
    budgetType: 'fixed',
    description:
      'I have a logo I like from Pinterest. Need someone to recreate it exactly for my business. Quick job.',
    skills: ['Logo Design', 'Adobe Illustrator'],
    clientQuality: 'low',
    clientInfo: { spend: '$150+', rating: 2.9, location: 'United States', hireRate: '10%' },
    competition: 'high',
    matchScore: 8,
    verdict: 'skip',
    scoreBreakdown: {
      nicheMatch: 15,
      budgetQuality: 5,
      clientQuality: 10,
      competition: 15,
      clarity: 70,
      urgency: 80,
      portfolioMatch: 10,
      conversionChance: 3,
    },
    redFlags: [
      'Likely copyright infringement',
      'Extremely low budget',
      'Very low client rating',
    ],
    portfolioMatchIds: [],
    suggestedAngle: 'Skip — ethical and business red flags.',
    discoveryQuestion: '',
    postedDate: '2026-06-14T10:00:00Z',
    receivedDate: '2026-06-14T10:00:00Z',
    jobUrl: 'https://www.upwork.com/jobs/~9998887777',
    stage: 'found',
    outcome: null,
  },
]
